config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    'tasks', to: 'tasks#index'
  get    'tasks/new', to: 'tasks#new'
  post   'tasks', to: 'tasks#create'
  get    'tasks/:id', to: 'tasks#show', as: :task
  get    'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch  'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index         # GET /tasks
    @tasks = Task.all
  end

  def show          # GET /task/:id
  end

  def new           # GET /tasks/new
    @task = Task.new
  end

  def create        # POST /tasks
    @task = Task.new(task_params)
    redirect_to tasks_path
  end

  def edit          # GET /task/:id/edit
  end

  def update        # PATCH /task/:id
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy       # DELETE /task/:id
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :tittle %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <div class="check">
    <%= f.check_box :completed %>
    <%= f.label :completed %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<h1> Edit task </h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<% @tasks.each do |task| %>
<p>
  <% if task.completed %>
    <i class="far fa-check-square"></i>
  <% else %>
    <i class="far fa-square"></i>
  <% end %>
    <%= link_to task.title, task_path(task) %>

     <%= link_to task_path(task), method: :delete, data: { confirm: "Are you sure?"} do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
</p>
<% end %>

<%= link_to "Add a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1> New Task </h1>

<%= render 'form' %>

<p><%= link_to "Back to list", tasks_path %></p>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<h3><%= @task.details %></h3>

<% if @task.completed %>
<p><i class="far fa-check-square"></i> Completed!</p>
<% else %>
<p><i class="far fa-square"></i> Not completed yet</p>
<% end %>

<%= link_to "Back to all", tasks_path %>
<%= link_to "Edit this task", edit_task_path %>